# note that on Windows we will not have the recommneded XFS filesystem
# so we will have degraded performance
volumes:
  scylla-data-node1:
    driver: local
  scylla-data-node2:
    driver: local
  scylla-data-node3:
    driver: local

services:
  scylla-node1:
    image: scylladb/scylla:6.0
    container_name: scylla-node1
    # reactor backend -
    #   this updates the advanced socket config.
    #   Read more: https://java-driver.docs.scylladb.com/stable/manual/core/configuration/reference/README.html
    #   the above readme links to their Java driver, but this was the only reference I could find that referenced roughly what I was looking for
    command: --smp 1 --reactor-backend=epoll --experimental 0
    environment:
      - "SCYLLA_JMX_ADDR=ja 0.0.0.0"
      - "SCYLLA_JMX_REMOTE=r"
    expose:
      - "7199" # JMX service port
    ports:
      - "9042:9042" # allow querying scylla (non SSL)
      - "10000:10000" # REST API server
    volumes:
      - scylla-data-node1:/var/lib/scylla
      - ./scylla.yml:/etc/scylla/scylla.yml

  scylla-node2:
    image: scylladb/scylla:6.0
    container_name: scylla-node2
    command: --smp 1 --seeds=scylla-node1 --reactor-backend=epoll --experimental 0
    environment:
      - "SCYLLA_JMX_ADDR=ja 0.0.0.0"
      - "SCYLLA_JMX_REMOTE=r"
    expose:
      - "7199"
    volumes:
      - scylla-data-node2:/var/lib/scylla
      - ./scylla.yml:/etc/scylla/scylla.yml
    depends_on:
      - scylla-node1

  scylla-node3:
    image: scylladb/scylla:6.0
    container_name: scylla-node3
    command: --smp 1 --seeds=scylla-node1 --reactor-backend=epoll --experimental 0
    environment:
      - "SCYLLA_JMX_ADDR=ja 0.0.0.0"
      - "SCYLLA_JMX_REMOTE=r"
    expose:
      - "7199"
    volumes:
      - scylla-data-node3:/var/lib/scylla
      - ./scylla.yml:/etc/scylla/scylla.yml
    depends_on:
      - scylla-node1
