volumes:
  scylla-data-node1:
    driver: local
  scylla-data-node2:
    driver: local
  scylla-data-node3:
    driver: local

services:
  scylla-node1:
    image: scylladb/scylla
    container_name: scylla-node1
    command: --smp 1 --reactor-backend=epoll --developer-mode 1 --experimental 0
    environment:
      - "SCYLLA_JMX_ADDR=ja 0.0.0.0"
      - "SCYLLA_JMX_REMOTE=r"
    expose:
      - "7199" # JMX service port
      - "9042" # allow querying scylla
    volumes:
      - scylla-data-node1:/var/lib/scylla

  scylla-node2:
    image: scylladb/scylla
    container_name: scylla-node2
    command: --smp 1 --seeds=scylla-node1 --reactor-backend=epoll --developer-mode 1 --experimental 0
    environment:
      - "SCYLLA_JMX_ADDR=ja 0.0.0.0"
      - "SCYLLA_JMX_REMOTE=r"
    expose:
      - "7199"
    volumes:
      - scylla-data-node2:/var/lib/scylla
    depends_on:
      - scylla-node1

  scylla-node3:
    image: scylladb/scylla
    container_name: scylla-node3
    command: --smp 1 --seeds=scylla-node1 --reactor-backend=epoll --developer-mode 1 --experimental 0
    environment:
      - "SCYLLA_JMX_ADDR=ja 0.0.0.0"
      - "SCYLLA_JMX_REMOTE=r"
    expose:
      - "7199"
    volumes:
      - scylla-data-node3:/var/lib/scylla
    depends_on:
      - scylla-node1
